import React, { useState, useEffect } from 'react';
import { Clock, ArrowLeftRight, Settings2, Sun, Moon, Star, Trash2 } from 'lucide-react';
import { DateTime } from 'luxon';

const timeZoneOptions = [
  { value: 'Africa/Addis_Ababa', label: 'Addis Ababa (GMT+3) [Africa/Addis_Ababa]' },
  { value: 'Europe/Amsterdam', label: 'Amsterdam (GMT+2) [Europe/Amsterdam]' },
  { value: 'Europe/Athens', label: 'Athens (GMT+3) [Europe/Athens]' },
  { value: 'Asia/Bangkok', label: 'Bangkok (GMT+7) [Asia/Bangkok]' },
  { value: 'America/Boston', label: 'Boston (GMT-4) [America/Boston]' },
  { value: 'Australia/Brisbane', label: 'Brisbane (GMT+10) [Australia/Brisbane]' },
  { value: 'Europe/Brussels', label: 'Brussels (GMT+2) [Europe/Brussels]' },
  { value: 'Africa/Cairo', label: 'Cairo (GMT+2) [Africa/Cairo]' },
  { value: 'Africa/Casablanca', label: 'Casablanca (GMT+1) [Africa/Casablanca]' },
  { value: 'America/Chicago', label: 'Chicago (GMT-5) [America/Chicago]' },
  { value: 'Europe/Copenhagen', label: 'Copenhagen (GMT+2) [Europe/Copenhagen]' },
  { value: 'America/Denver', label: 'Denver (GMT-6) [America/Denver]' },
  { value: 'Asia/Dubai', label: 'Dubai (GMT+4) [Asia/Dubai]' },
  { value: 'Asia/Ho_Chi_Minh', label: 'Ho Chi Minh City (GMT+7) [Asia/Ho_Chi_Minh]' },
  { value: 'Asia/Hong_Kong', label: 'Hong Kong (GMT+8) [Asia/Hong_Kong]' },
  { value: 'Asia/Jakarta', label: 'Jakarta (GMT+7) [Asia/Jakarta]' },
  { value: 'Africa/Johannesburg', label: 'Johannesburg (GMT+2) [Africa/Johannesburg]' },
  { value: 'Asia/Karachi', label: 'Karachi (GMT+5) [Asia/Karachi]' },
  { value: 'Asia/Kolkata', label: 'India (GMT+5:30) [Asia/Kolkata]' },
  { value: 'Asia/Kuala_Lumpur', label: 'Kuala Lumpur (GMT+8) [Asia/Kuala_Lumpur]' },
  { value: 'Asia/Kuwait', label: 'Kuwait City (GMT+3) [Asia/Kuwait]' },
  { value: 'Africa/Lagos', label: 'Lagos (GMT+1) [Africa/Lagos]' },
  { value: 'Europe/Lisbon', label: 'Lisbon (GMT+1) [Europe/Lisbon]' },
  { value: 'America/Los_Angeles', label: 'Los Angeles (GMT-7) [America/Los_Angeles]' },
  { value: 'Europe/Madrid', label: 'Madrid (GMT+2) [Europe/Madrid]' },
  { value: 'Australia/Melbourne', label: 'Melbourne (GMT+11) [Australia/Melbourne]' },
  { value: 'America/Mexico_City', label: 'Mexico City (GMT-5) [America/Mexico_City]' },
  { value: 'America/Miami', label: 'Miami (GMT-4) [America/Miami]' },
  { value: 'America/Montreal', label: 'Montreal (GMT-4) [America/Montreal]' },
  { value: 'Europe/Moscow', label: 'Moscow (GMT+3) [Europe/Moscow]' },
  { value: 'Africa/Nairobi', label: 'Nairobi (GMT+3) [Africa/Nairobi]' },
  { value: 'America/New_York', label: 'New York (GMT-4) [America/New_York]' },
  { value: 'Europe/Oslo', label: 'Oslo (GMT+2) [Europe/Oslo]' },
  { value: 'Europe/Paris', label: 'Paris (GMT+2) [Europe/Paris]' },
  { value: 'Australia/Perth', label: 'Perth (GMT+8) [Australia/Perth]' },
  { value: 'America/Phoenix', label: 'Phoenix (GMT-7) [America/Phoenix]' },
  { value: 'Asia/Riyadh', label: 'Riyadh (GMT+3) [Asia/Riyadh]' },
  { value: 'Europe/Rome', label: 'Rome (GMT+2) [Europe/Rome]' },
  { value: 'America/San_Francisco', label: 'San Francisco (GMT-7) [America/San_Francisco]' },
  { value: 'America/Sao_Paulo', label: 'São Paulo (GMT-3) [America/Sao_Paulo]' },
  { value: 'Asia/Seoul', label: 'Seoul (GMT+9) [Asia/Seoul]' },
  { value: 'Asia/Shanghai', label: 'Shanghai (GMT+8) [Asia/Shanghai]' },
  { value: 'Asia/Singapore', label: 'Singapore (GMT+8) [Asia/Singapore]' },
  { value: 'Europe/Stockholm', label: 'Stockholm (GMT+2) [Europe/Stockholm]' },
  { value: 'Australia/Sydney', label: 'Sydney (GMT+11) [Australia/Sydney]' },
  { value: 'Asia/Taipei', label: 'Taipei (GMT+8) [Asia/Taipei]' },
  { value: 'Asia/Tel_Aviv', label: 'Tel Aviv (GMT+3) [Asia/Tel_Aviv]' },
  { value: 'America/Toronto', label: 'Toronto (GMT-4) [America/Toronto]' },
  { value: 'America/Vancouver', label: 'Vancouver (GMT-7) [America/Vancouver]' },
  { value: 'Europe/Vienna', label: 'Vienna (GMT+2) [Europe/Vienna]' },
  { value: 'Europe/Warsaw', label: 'Warsaw (GMT+2) [Europe/Warsaw]' }
].sort((a, b) => a.label.localeCompare(b.label));

// Rest of the TimeZoneConverter component code remains unchanged
